apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  labels:
    app: sb-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: sb-app
  template:
    metadata:
      labels:
        app: sb-app 
    spec:
      containers:
      - name: sb-app
        image: kaazim/sb-app:latest 
        ports:
        - containerPort: 8900





apiVersion: v1
kind: Service
metadata:
  name: sb-app service
spec:
  selector:
    app: sb-app 
  type: NodePort
  ports:
  - protocol: TCP
    port: 8900 
    targetPort: 8900
